apiVersion: v1
kind: Service
metadata:
  name: helloworld-lb
  labels:
    app: helloworld
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: helloworld
