apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deploy
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: helloworld
        image: helloworld:1
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
