root: true
env:
  node: true
  browser: true
  es2020: true
extends:
  - "plugin:vue/essential"
  - "eslint:recommended"
  - "@vue/prettier"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  parser: "babel-eslint"
rules:
  no-console: "warn"
  no-debugger: "warn"
  prettier/prettier:
    - warn
    - arrowParens: always
      bracketSpacing: true
      endOfLine: lf
      printWidth: 80
      semi: true
      singleQuote: true
      tabWidth: 2
      trailingComma: all
